#!/bin/bash

# Define the sync destination and device IP
syncDestination="/media/chris/KOBOeReader"
deviceIp="192.168.0.41"

# Mount the remote directory using sshfs
sshfs root@$deviceIp:/mnt/onboard $syncDestination

# Check if the sync destination is mounted
if mountpoint -q $syncDestination; then
    echo "KOBOeReader is mounted"

    # Run the program with the necessary options
    python program.py -s

    # Unmount the remote directory
    fusermount -u $syncDestination
    echo "KOBOeReader is unmounted"
else
    echo "Failed to mount KOBOeReader"
fi

echo "Done"
